#pragma once
#include "stdafx.h"

// control ids of the settings window (shared with the standalone probes)
enum {
    IDC_TAB = 2000, IDC_CLOSE,
    IDC_P1_PAGES, IDC_P1_ADDPAGE, IDC_P1_RENPAGE, IDC_P1_DELPAGE,
    IDC_P1_SLOTS, IDC_P1_ADDSLOT, IDC_P1_DELSLOT, IDC_P1_UPSLOT, IDC_P1_DOWNSLOT,
    IDC_P1_TYPE, IDC_P1_NAME, IDC_P1_KEYS, IDC_P1_KEYPRESET, IDC_P1_TARGET, IDC_P1_BRFILE, IDC_P1_BRFOLDER,
    IDC_P1_ICONPREV, IDC_P1_ICONPRESET, IDC_P1_ICONIMG, IDC_P1_ICONCLEAR,
    IDC_P1_MODWIN, IDC_P1_MODCTRL, IDC_P1_MODALT, IDC_P1_MODSHIFT,
    IDC_P1_KEYS_L, IDC_P1_KEYS_HINT, IDC_P1_TGT_L, IDC_P1_WHEELVIEW,
    IDC_P2_PREVIEW, IDC_P2_SECTORS, IDC_P2_ROTATION, IDC_P2_DIAMETER, IDC_P2_ICONSIZE, IDC_P2_GAP,
    IDC_P2_ANIMMS, IDC_P2_ANIMCHK, IDC_P2_BGMODE, IDC_P2_COLORMODE,
    IDC_P2_BGCOLOR, IDC_P2_BGOPACITY,
    IDC_P2_HOVERCOLOR, IDC_P2_BORDCOLOR, IDC_P2_BORDW, IDC_P2_TEXTCOLOR,
    IDC_P2_BGCOLOR_L, IDC_P2_HOVERCOLOR_L, IDC_P2_BORDCOLOR_L, IDC_P2_TEXTCOLOR_L,
    IDC_P2_LABELS, IDC_P2_LABELSIZE, IDC_P2_LABELFONT, IDC_P2_CENTER, IDC_P2_CENTERTEXT,
    IDC_P2_GLASSBLUR, IDC_P2_GLASSHEIGHT, IDC_P2_GLASSAMT,
    IDC_P2_GLASSCHROMA, IDC_P2_GLASSHL, IDC_P2_GLASSVIB,
    IDC_P2_CUTRES, IDC_P2_CUTFPS,
    IDC_P2_HOVERAUTO,
    IDC_P3_ENABLE, IDC_P3_BUTTON, IDC_P3_THRESHOLD, IDC_P3_WHEELSENS, IDC_P3_TRAY, IDC_P3_AUTOSTART,
    IDC_P3_EXCL, IDC_P3_EXCLADD, IDC_P3_EXCLDEL, IDC_P3_EXCLEDIT,
    IDC_P3_EXCLFULL, IDC_P3_EXCLRUN,
};

void OpenSettings();
void SettingsFlushAndClose();   // used at app exit
bool IsSettingsWindow(HWND h);
